"""Writes docs/THIRD-PARTY.md: the libraries and fonts built into prev,
with their licenses. Run from the repository root after changing
dependencies:

    python3 scripts/third-party.py
"""

import json
import subprocess
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "THIRD-PARTY.md"

# What is built in but not a Rust crate, or whose crate carries C code
# with a license of its own.
BUNDLED = [
    ("MuPDF", "AGPL-3.0-or-later", "PDF engine, built from source through the mupdf crate", "https://mupdf.com"),
    ("libheif", "LGPL-3.0-or-later", "HEIC and AVIF decoding; bundled on Windows, macOS and in the Flatpak, the system's elsewhere", "https://github.com/strukturag/libheif"),
    ("libde265", "LGPL-3.0-or-later", "HEVC decoder for libheif; bundled on Windows, macOS and in the Flatpak", "https://github.com/strukturag/libde265"),
    ("libaom", "BSD-2-Clause", "AV1 decoder for libheif; bundled on Windows and macOS", "https://aomedia.googlesource.com/aom"),
    ("wl-clipboard", "GPL-3.0-or-later", "clipboard images on Wayland, run as a separate program; bundled in the Flatpak", "https://github.com/bugaevc/wl-clipboard"),
    ("Roboto Flex", "OFL-1.1", "interface font", "https://github.com/googlefonts/roboto-flex"),
    ("Dancing Script", "OFL-1.1", "font for typed signatures", "https://github.com/googlefonts/DancingScript"),
    ("Material Symbols Rounded", "Apache-2.0", "icons", "https://github.com/google/material-design-icons"),
    ("smithay-clipboard", "MIT", "vendored with a drag and drop patch, see vendor/PATCHES.md", "https://github.com/Smithay/smithay-clipboard"),
    ("iced_graphics, iced_widget", "MIT", "vendored with right to left text input patches, see vendor/PATCHES.md", "https://github.com/iced-rs/iced"),
    ("winit", "Apache-2.0", "vendored with patches for the keyboard layout in use and the files macOS opens, see vendor/PATCHES.md", "https://github.com/rust-windowing/winit"),
]


def dependencies():
    """Every package the prev binary is built from, but prev's own."""
    metadata = json.loads(
        subprocess.check_output(
            ["cargo", "metadata", "--format-version", "1", "--locked"], cwd=ROOT
        )
    )
    packages = {package["id"]: package for package in metadata["packages"]}
    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    root = next(id for id, package in packages.items() if package["name"] == "prev")
    seen, stack = set(), [root]
    while stack:
        id = stack.pop()
        if id in seen:
            continue
        seen.add(id)
        for dep in nodes[id]["deps"]:
            # Build scripts and normal dependencies end up in the binary or
            # shape it; development dependencies do not.
            if any(kind["kind"] in (None, "build") for kind in dep["dep_kinds"]):
                stack.append(dep["pkg"])
    own = {"prev", "prev-image", "prev-pdf", "prev-store"}
    return sorted(
        (packages[id] for id in seen if packages[id]["name"] not in own),
        key=lambda package: (package["name"], package["version"]),
    )


def main():
    crates = dependencies()
    by_license = defaultdict(list)
    for package in crates:
        license = package.get("license") or "see the crate"
        by_license[license].append(f'{package["name"]} {package["version"]}')
    lines = [
        "# Third-party components",
        "",
        "prev is licensed under the GNU Affero General Public License, version 3",
        "or later (see LICENSE). It is built from the components below, each",
        "under its own license. This file is generated by",
        "`scripts/third-party.py`.",
        "",
        "## Bundled libraries and fonts",
        "",
        "| Component | License | Use |",
        "|---|---|---|",
    ]
    for name, license, use, url in BUNDLED:
        lines.append(f"| [{name}]({url}) | {license} | {use} |")
    lines += [
        "",
        f"## Rust crates ({len(crates)})",
        "",
        "Grouped by license, as each crate declares it.",
        "",
    ]
    for license in sorted(by_license, key=lambda license: (-len(by_license[license]), license)):
        lines.append(f"### {license}")
        lines.append("")
        lines.append(", ".join(by_license[license]))
        lines.append("")
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(crates)} crates")


if __name__ == "__main__":
    main()
