[package]
name = "prev"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
ashpd = { version = "0.13", default-features = false, features = ["async-io", "file_chooser", "open_uri", "print"] }
bytes = "1"
iced = { version = "0.14", features = ["advanced", "highlighter", "image-without-codecs", "markdown"] }
image = { version = "0.25", default-features = false }
raw-window-handle = "0.6"
serde = { version = "1", features = ["derive"] }
smithay-clipboard = "0.7"
toml = "1"
prev-image.workspace = true
prev-pdf.workspace = true
prev-store.workspace = true

[dev-dependencies]
tempfile = "3"
